
name: "Release to Crates"

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create release
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: login
      uses: actions-rs/cargo@v1
      with:
        command: login
        args: ${{ secrets.CRATES_IO_TOKEN }}
    - name: publish main
      uses: actions-rs/cargo@v1
      with:
        command: publish
