name: "Release to draft"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Specify tag to create"
        required: true

jobs:
  build:
    name: Build
    strategy:
      matrix:
        target:
          - target: windows
            os: windows-latest
            make: make binary
            binary_path: target/release/discord-rpc-gui.exe

          - target: linux
            os: ubuntu-18.04
            make: make appimage
            binary_path: discord-rpc-gui.AppImage

          - target: macos
            os: macos-latest
            make: make dmg MACOS=1
            binary_path: target/release/osx/discord-rpc-gui.dmg
          - target: macos-tar
            os: macos-latest
            make: make tar MACOS=1
            binary_path: target/release/discord-rpc-gui.tar.gz

    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        if: ${{ matrix.target.os == 'ubuntu-18.04' }}
        run: sudo apt install libxkbcommon-dev

      - name: Do we need linuxdeploy?
        if: ${{ matrix.target.os == 'ubuntu-18.04' }}
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Do we need GNU tar? # Fix for macos caching, https://github.com/actions/cache/issues/403
        if: ${{ matrix.target.os == 'macos-latest' }}
        run: |
          brew install gnu-tar
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH

      - name: Build
        run: ${{ matrix.target.make }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.target }}
          path: ${{ matrix.target.binary_path }}

  create-release:
    needs: build
    name: Create Release
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }}
          draft: true
          prerelease: false

  add-assets:
    needs: create-release
    name: Add Assets

    strategy:
      matrix:
        target:
          - artifact: windows
            artifact_name: discord-rpc-gui.exe
            asset_name: discord-rpc-gui.exe
            asset_type: application/x-dosexec

          - artifact: linux
            artifact_name: discord-rpc-gui.AppImage
            asset_name: discord-rpc-gui.AppImage
            asset_type: application/x-executable

          - artifact: macos
            artifact_name: discord-rpc-gui.dmg
            asset_name: discord-rpc-gui.dmg
            asset_type: application/octet-stream
          - artifact: macos-tar
            artifact_name: discord-rpc-gui.tar.gz
            asset_name: discord-rpc-gui.tar.gz
            asset_type: application/gzip

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.target.artifact }}
          path: ${{ matrix.target.artifact }}

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ matrix.target.artifact }}/${{ matrix.target.artifact_name }}
          asset_name: ${{ matrix.target.asset_name }}
          asset_content_type: ${{ matrix.target.asset_type }}
